name: Upload website to s3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master #action is used to fetch the repository's code
      - uses: jakejarvis/s3-sync-action@master #action is used to synchronize the website directory (change this to match your actual website directory) with the specified S3 bucket.
      with:
        args: --acl public-read --follow-symlinks --delete #--delete argument removes any files in the S3 bucket that are not present in the local website directory.
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'website'
